services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=BASE
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    command: sh -c "python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code/
      - static_volume:/src/mysite/static
    depends_on:
      - postgres
    expose:
      - "8000"
    networks:
      - main
    restart: always
  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - /static:/src/mysite/static
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  main:
volumes:
  postgres_data:
  static_volume: